### ISSUE TITLE
tsc is deprecated

### ISSUE THREAD

**Issue by ostpol** [n-thumann/IPTV-ReStream#90]
Hey,

according to [npm](https://www.npmjs.com/package/tsc) tsc is deprecated.

```
pi@tvpi:~/downloads/IPTV-ReStream $ npm run build

> iptv-restream@1.2.0 build
> tsc

error TS5014: Failed to parse file 'tsconfig.json': Unexpected token / in JSON at position 74.
npm ERR! code 1
npm ERR! path /home/pi/downloads/IPTV-ReStream
npm ERR! command failed
npm ERR! command sh -c tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2021-01-04T15_43_13_012Z-debug.log
```

**Comment by ostpol** [comment]
Well. I've re-cloned the repo. It's working now. Maybe tsconfig.json got somehow messed up.

**Comment by n-thumann** [comment]
This probably occurred because you have [tsc](https://www.npmjs.com/package/tsc) globally installed and forgot to run `npm install` before building. Because of that, `npm run build` will fall back to use the deprecated `tsc` (which cannot handle comments in JSON) and not current `tsc` of the [typescript](https://www.npmjs.com/package/typescript) package that is installed automatically ✌️
